import "./globals.css";
import Navbar from "../components/homepage/Navbar";
import Footer from "@/components/homepage/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html>
      <body>
        <div className="">
          <Navbar></Navbar>
        </div>

        <div>{children}</div>

        <div>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
