import "./globals.css";
import Navbar from "../components/homepage/Navbar";
import Footer from "@/components/homepage/Footer";
import { AuthProvider } from "@/lib/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <AuthProvider>
          <div className="">
            <Navbar></Navbar>
          </div>

          <div>{children}</div>

          <div>
            <Footer></Footer>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
